handsomeliuyang/taro

packages/taro-cli-convertor/src/util/index.ts
packages/taroize/src/wxml.ts

1、convert相关代码内，引用导入添加.js后缀，避免编译时的模块找不到问题（导入utils/auth -> utils/auth.js）
2、convert相关代码内，属性wx:show属性替换为wx:if，避免编译报错（wx:show已无法在微信小程序官方文档搜索到）

convert修改：添加.js后缀，替换wx:show属性

---

packages/taroize/src/template.ts
packages/taroize/src/wxml.ts

微信小程序支持slot标签的值为空，但转换工具对此无法转换
当检测到slot的值为空时，为slot赋值‘taroslot’

'修复转换时slot值为空的错误，为slot赋值taroslot'

---

packages/taro-transformer-wx/src/index.ts
packages/taro-transformer-wx/src/wxs.ts
packages/taroize/src/wxml.ts

微信小程序转taro时，wxs标签和wxs文件中getRegExp转换为new RegExp

fix: 微信小程序转taro时，wxs标签和wxs文件中getRegExp转换为new RegExp

---

packages/taroize/src/wxml.ts

修复解构符...转换报错
在babel6中解构符...对应的ast节点类型为SpreadProperty，在babel7中变更为SpreadElement，所以在代码转换成ast和变换后的ast转换成code的步骤中需要统一使用相同版本的babel，此处的修改是将代码转换时使用6.x的baylon更新为7.x的@babel/parser

fix: 修复解构符...转换报错

---

packages/taro-transformer-wx/package.json
packages/taro-transformer-wx/src/index.ts
packages/taroize/package.json
packages/taroize/src/utils.ts

修复async/await会转换成生成器函数，保留async/await
在之前的转换过程中，async/await会转换成生成器函数，如下
转化前：
转换后：

fix: 修复async/await会转换成生成器函数，保留async/await

---

packages/taro-components-mpharmony/package.json
packages/taro-components-mpharmony/src/components/image/style/index.css
packages/taro-components-mpharmony/src/components/pull-down-refresh/index.tsx
packages/taro-components-mpharmony/src/components/swiper/index.tsx
packages/taro-components-mpharmony/src/components/swiper/style/index.css
packages/taro-components-react/src/components/image/index.tsx
packages/taro-components-react/src/components/image/style/index.css
packages/taro-components/src/components/input/index.scss
pnpm-lock.yaml

Swiper组件重构；下拉刷新bug修改；其他组件样式与bug修改

---

examples/mini-program-example/src/pages/api/device/accelerometer/index.tsx
examples/mini-program-example/src/pages/api/device/network/index.tsx
examples/mini-program-example/src/pages/api/device/wifi/index.tsx
examples/mini-program-example/src/pages/api/interface/interaction/index.tsx

fix: 修复界面-交互的buttonList,以及其他没有更换buttonList组件的页面

---

examples/mini-program-example/src/components/buttonList/index.scss
examples/mini-program-example/src/components/buttonList/index.tsx

feat: 添加隐藏按钮,隐藏textarea输入框功能

---

packages/taro-cli-convertor/src/index.ts

自定义组件中文件名为index.xxx，引入时路径可以只到文件夹，此时报js文件找不到

fix: 修复自定义组件文件名为index时的引用问题

---

examples/mini-program-example/src/pages/api/media/image/index.tsx
examples/mini-program-example/src/pages/api/media/richText/index.tsx
packages/taro-mpharmony/src/api/media/EditorContext.ts

fix: 修改媒体-富文本的insertImage换行不生效等问题，增加富文本接口的可测试性
fix
鸿蒙（harmony）

fix: 修改媒体-富文本的insertImage换行不生效等问题，增加富文本的接口的可测试性

---

examples/mini-program-example/src/pages/api/media/video/index.tsx
packages/taro-components/src/components/video/video.tsx
packages/taro-mpharmony/src/api/media/EditorContext.ts

修改媒体-富文本的removeFormat无法清除文本样式的问题
fix
鸿蒙（harmony

fix: 修改媒体-富文本的removeFormat无法清除文本样式的问题

---

packages/taro-cli-convertor/src/index.ts

修复复制三方库时因为符号链接造成的一些问题
pnpm install安装依赖包，node_modules下的依赖包为快捷方式（符号链接），依赖包真正的位置在node_modules/.pnpm下
调用fs.readlinkSync读取链接地址

fix: 修复复制三方库时因为符号链接造成的一些问题

---

packages/taro-cli-convertor/src/util/index.ts

fix: 删去三方库复制时某些场景下pnpm包快捷方式地址的获取

---

packages/taro-cli-convertor/src/index.ts
packages/taro-cli-convertor/src/util/index.ts

问题：
修复wxss文件注释中引用自身导致的转换死循环
修复方案：
转换wxss文件时，不考虑注释中的引用

fix: 修复wxss文件注释中引用自身导致的转换死循环

---

packages/taro-cli-convertor/src/index.ts
packages/taro-cli-convertor/src/util/index.ts

支持配置不转换的页面
背景：
支持配置不转换的目录有两种
1、文件中引用的文件目录
2、页面

feat: 支持配置不转换的页面

---

packages/taro-cli-convertor/src/util/astConvert.ts
packages/taro-transformer-wx/src/functional.ts
packages/taro-transformer-wx/src/jsx.ts
packages/taro-transformer-wx/src/utils.ts

fix: 解决convertor编译过程中出现的类型报错

---

packages/taroize/src/template.ts
packages/taroize/src/wxml.ts

当前template转换后，会引入一些原生不支持的接口；
在template模板转换时引入装饰器@withWeapp，以适配这些接口，转换结果形如下图

fix: template模板转换引入装饰器@withWeapp

---

packages/taroize/src/wxml.ts

对于catch形式的自定义事件绑定，转换后会用this.privateStopNoop.bind（）进行包裹，其中调用了event接口e.stopPropagation() 。转换后的语句（ this.privateStopNoop.bind（this, this.xxx）），参数中的this不指向event，不支持e.stopPropagation() 接口
因此去掉this.privateStopNoop包裹

fix: 自定义事件绑定（catch:xxx）转换去除this.privateStopNoop包裹

---

packages/taroize/src/wxml.ts

对于扩展运算符语句（...xxx），babel提供的接口prase无法将其转换为AST；convert对形如 ...xxx,xxxx的同时带有扩展运算符和其他参数的语句提供了转换支持
添加对单独扩展运算符的语句的转换支持，并与上面的支持相合并

fix: 添加对一种扩展运算符语句（形如 ...xxx）的转换支持

---

packages/taroize/src/wxml.ts

把mode=""改成了mode="scaleToFill"(微信小程序的默认值)。由于mode=""被ast处理后重新转为代码会变成mode，并且mode=""在taro内表现与微信小程序内不同，所以改为默认值。

fix: 当设置图片mode=""时，转换改为默认值

---

packages/postcss-unit-transform/index.js

css样式转换转完后0.5px变为0px问题修复。
转十进制时<1的数字会被转为0，修正：<1数字直接改为1。

fix: css样式转换转完后0.5px变为0px问题修复

---

packages/taro-transformer-wx/src/index.ts
packages/taroize/package.json
packages/taroize/src/script.ts
packages/taroize/src/utils.ts
pnpm-lock.yaml

fix: 导入导出commonjs转es6，代码回退

---

packages/postcss-unit-transform/index.js

修正转换css样式单位会匹配到图片url里刚好数字+px的字符串导致被错误转换的问题

fix: 修正转换css样式单位会匹配到图片url里刚好数字+px的字符串导致被错误转换的问题

---

packages/taro-cli-convertor/src/index.ts

对页面三方组件的导入进行过滤，导致wxs导入的组件丢失
对过滤条件进行修改，使得能够识别wxs导入的组件，从而成功导入

fix: 修复因过滤导入而漏掉wxs导入的错误

---

packages/taroize/src/wxml.ts

修复部分情况wx:key没转成key的问题，并format了代码

fix: 修复部分情况wx:key没转成key的问题

---

packages/taro-cli-convertor/src/index.ts
packages/taro-cli-convertor/src/util/astConvert.ts
packages/taroize/src/script.ts
packages/taroize/src/utils.ts

兼容打包成commonjs格式的组件或页面转换
场景：
组件打包成commonjs的格式，即在js中出现module.exports，如果导出的taro为esm的import形式，则出现了混用报错，此提交为兼容这类情况

fix: 兼容打包成commonjs格式的组件或页面转换

---

packages/taroize/src/template.ts
packages/taroize/src/wxml.ts

当前template转换后，部分所需变量没有被抽取到props的data中
修复了变量抽取不全的问题

fix: 修复template转换后变量抽取不全的问题

---

packages/taroize/src/wxml.ts

wx:if和wx:for合用的场景，转换使用replaceWith进行拆分
此时如果父组件使用了wx:if，replaceWith会因为检查而产生异常（Container is falsy）
使用try/catch捕获这个异常，使replaceWith能够顺利替换

fix: wx:if和wx:for合用时父组件使用wx:if导致replaceWith产生异常

---

packages/taroize/src/wxml.ts

template中的方法写入到props后，props的位置应在render{}中，转换对BlockStatement进行遍历，没有其他约束，就会在所有的{}中插入props
添加path.stop，在render{}中处理props后，就停止遍历

fix: template中的方法写入到props后，props出现在预期位置以外的地方

---

packages/taro-mpharmony/src/api/device/clipboard.ts

修复执行setClipBoardData样例，手机没有弹出提示内容
fix
鸿蒙（harmony）

fix: 修复执行setClipBoardData样例，手机没有弹出提示内容

---

packages/taro-cli-convertor/package.json
packages/taro-cli-convertor/src/index.ts
packages/taro-cli-convertor/src/util/astConvert.ts
packages/taro-transformer-wx/package.json
packages/taro-transformer-wx/src/index.ts
packages/taroize/src/index.ts
packages/taroize/src/utils.ts
packages/taroize/src/wxml.ts
pnpm-lock.yaml

1、从ast生成代码时不做prettier的格式化处理，会影响代码前后的映射关系
2、babel.transformSync生成的ast中loc无法设置filename，更换为babylon的parse
3、wxml解析成ast时将position属性转换为loc属性
4、wxml的ast与js的ast合并是格式会错乱，在行前增加6个空格保持格式对齐

feat: 转换时生成sourceMap，获取源文件和目标文件的对应关系

---

packages/taro-transformer-wx/src/index.ts
packages/taroize/src/script.ts
packages/taroize/src/utils.ts

fix: 代码回退，修复import和解构符不支持的问题

---

packages/taroize/src/wxml.ts

修复template中data数据为多个时转换异常
微信源码：
<template is="huangye" data="{{name, age}}"/>
正常转换应该为：
<template is="huangye" data="{{name, name1}}"/>
当前异常转换：
<HuangyeTmpl data={(name, name1)}></HuangyeTmpl>

fix: 修复template中data数据为多个时转换异常

---

packages/taro-cli-convertor/src/index.ts

修复template is为变量转换异常问题
修复的异常场景：is的value为变量，如下
<template is="{{core}}" ></template>

fix: 修复template is为变量转换异常问题

---

packages/taroize/src/template.ts

parseTemplate添加对path是否是JSXElement的判断，修复template和hidden合用时的转换错误

fix: parseTemplate添加对path是否是JSXElement的判断，修复template和hidden合用时的转换错误

---

packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap
packages/taro-cli-convertor/__tests__/script.test.ts
packages/taro-cli-convertor/src/index.ts

/
修复template模板使用单个字母命名转换到H5报错问题和补充测试用例

fix: 修复template模板使用单个字母命名转换到H5报错问题和补充测试用例

---

packages/taro-cli-convertor/__tests__/__snapshots__/index.test.ts.snap
packages/taro-cli-convertor/__tests__/index.test.ts
packages/taroize/__tests__/__snapshots__/template.test.ts.snap
packages/taroize/__tests__/event.test.ts
packages/taroize/__tests__/template.test.ts
packages/taroize/__tests__/wxml.test.ts
packages/taroize/src/wxml.ts

补充历史测试用例：
1、data数据添加可选链操作符
2、组件、模板按需导入
3、模板套用，其中的数据和方法传递
4、部分catch事件，hidden属性解析
修复转换错误
形如(a ,b ,c...)转换，原先正则匹配缺失了对空格的检测

fix: 补充历史测试用例，修复一处转换错误

---

packages/taro-components/src/components/video/video.tsx

**问题：** 视频组件中，全屏后点击浏览器的退出全屏按钮报错：Uncaught (in promise) TypeError : Failed to execute ‘exitFullScreen’ on ‘Document’: Document not active
**原因：** 全屏后，"退出全屏"是浏览器按钮是浏览器内部按钮，非html按钮，点击"退出全屏"按钮是浏览器内部实现功能。此时再次调用exitFullscreen反而会报错。
**修复方案：** 区分出退出全屏方法是由浏览器调用还是api调用，对浏览器调用来源的不再执行exitFullscreen方法。

fix: 视频组件，浏览器退出全屏出错

---

packages/taro-h5/src/api/ui/tab-bar.ts

fix: 修复setTabBarBadge可显示的中文字符最多两个

---

packages/taro-components/src/components/map/map.tsx
packages/taro-mpharmony/src/api/media/map/MapContext.ts

fix: 修复异常id处理

---

packages/postcss-unit-transform/index.js
packages/taroize/__tests__/wxml.test.ts
packages/taroize/src/wxml.ts

/
现状：对于style中绝对值小于1的px/rpx转换成1rem
更改：对于style中绝对值小于1的px/rpx单位转换成rem，但值不变

fix: 内联style属性中绝对值小于1px/rpx转为rem

---

packages/postcss-unit-transform/index.js

fix: wxss样式转换时为保证在h5显示比例相同需要乘以2倍

---

packages/taro-components/src/components/live-player/live-player.tsx

fix: 修复live-player全屏退出导航栏显示滞后问题

---

packages/taro-cli-convertor/__tests__/__snapshots__/index.test.ts.snap
packages/taro-cli-convertor/__tests__/index.test.ts
packages/taro-cli-convertor/src/index.ts
packages/taro-cli-convertor/src/util/index.ts

/
feat: 新增使用 resolveAlias 配置项用来自定义模块路径的映射规则

feat: 新增使用 resolveAlias 配置项用来自定义模块路径的映射规则

---

packages/taro-cli-convertor/__tests__/config.test.ts

加了convertor里日志：关于utils文件夹里没有index.js文件的报错
- [X ] 微信小程序

feat: taro-cli-convertor部分日志测试用例

---

packages/taro-with-weapp/__tests__/lifecycle.jsx
packages/taro-with-weapp/__tests__/props.jsx
packages/taro-with-weapp/__tests__/state.jsx

fix: 修复taro-with-weapp的测试用例

---

packages/taro-mpharmony/src/api/network/download.ts
packages/taro-mpharmony/src/utils/handler.ts

在downloadTask中回调注册前增加一次判断，过滤掉已经注册的回调函数

fix: 修复downloadTask中回调注册多次导致无法一次取消问题

---

packages/taro-mpharmony/src/api/route/index.ts
packages/taro-mpharmony/src/api/storage/index.ts
packages/taro-platform-mpharmony/build/config/harmony-definition.json
packages/taro-platform-mpharmony/src/program.ts

fix: mpharmony平台路由api不要tree-shaking处理
