handsomeliuyang/taro

examples/mini-program-example/src/pages/index/index.scss, examples/mini-program-example/src/pages/index/index.tsx, packages/taro-components-mpharmony/src/components/index.ts, packages/taro-components-mpharmony/src/components/label/label.tsx
=> Release 3.6.8 app zcy

packages/taro-cli-convertor/bin/taro-convert, packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taroize/package.json, packages/taroize/src/index.ts, packages/taroize/src/script.ts, packages/taroize/src/utils.ts
=> feat: 新增对微信小程序ts工程的解析

examples/mini-program-example/src/pages/component/index/index.tsx
=> 'root-portal'组件的Demo状态

examples/mini-program-example/src/app.config.ts, examples/mini-program-example/src/pages/component/canvas/canvas.js, examples/mini-program-example/src/pages/component/canvas/canvas.scss, examples/mini-program-example/src/pages/component/index/index.tsx, examples/mini-program-example/src/pages/component/sticky-header/sticky-header.tsx, examples/mini-program-example/src/pages/component/swiper/swiper.scss, examples/mini-program-example/src/pages/component/video/video.js
1. StickHeader与StickSction的例子
2. Swiper例子优化
3. Video组件例子优化
4. Canvas例子补充
=> Example更新：1. StickHeader与StickSction的例子添加；2. Swiper例子优化；3. Video组件例子优化；4. Canvas例子添加

packages/taro-transformer-wx/src/create-html-element.ts, packages/taro-transformer-wx/src/jsx.ts
fix: taro-transform-wx模块编译问题修复
=> fix: taro-transform-wx模块编译问题修复

packages/taro-mpharmony/src/api/location/index.ts, packages/taro-mpharmony/src/api/location/offLocationChange.ts, packages/taro-mpharmony/src/api/location/offLocationChangeError.ts, packages/taro-mpharmony/src/api/location/onLocationChange.ts, packages/taro-mpharmony/src/api/location/onLocationChangeError.ts, packages/taro-mpharmony/src/api/location/startLocationUpdate.ts, packages/taro-mpharmony/src/api/location/startLocationUpdateBackground.ts, packages/taro-mpharmony/src/api/location/stopLocationUpdate.ts, packages/taro-mpharmony/src/utils/index.ts
=> 添加位置相关API，桥接鸿蒙native

examples/mini-program-example/src/pages/api/device/bettery/index.tsx, examples/mini-program-example/src/pages/api/device/bluetoothGeneral/index.tsx, examples/mini-program-example/src/pages/api/device/contact/index.tsx, examples/mini-program-example/src/pages/api/device/gyroscope/index.tsx, examples/mini-program-example/src/pages/api/device/phoneCall/index.tsx, examples/mini-program-example/src/pages/api/device/screen/index.tsx, examples/mini-program-example/src/pages/api/device/wifi/index.tsx, examples/mini-program-example/src/pages/api/file/index.tsx, examples/mini-program-example/src/pages/api/location/index.tsx, examples/mini-program-example/src/pages/api/media/camera/index.tsx, examples/mini-program-example/src/pages/api/media/image/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx, examples/mini-program-example/src/pages/api/openAPIS/biometricAuthorization/index.tsx
=> commit：Taro全量API example样例测试功能完善

packages/taro-mpharmony/src/api/location/getLocation.ts, packages/taro-mpharmony/src/api/location/offLocationChange.ts, packages/taro-mpharmony/src/api/location/offLocationChangeError.ts, packages/taro-mpharmony/src/api/location/onLocationChange.ts, packages/taro-mpharmony/src/api/location/onLocationChangeError.ts, packages/taro-mpharmony/src/api/location/startLocationUpdate.ts, packages/taro-mpharmony/src/api/location/startLocationUpdateBackground.ts, packages/taro-mpharmony/src/api/location/stopLocationUpdate.ts
修改location相关api回调参数，添加获取位置信息api桥接native
=> fix: 修改location相关api回调参数，添加获取位置信息api桥接native

examples/mini-program-example/package.json, examples/mini-program-example/src/pages/api/basics/basics/index.tsx, examples/mini-program-example/src/pages/api/basics/miniProgram/applicationLevelEvents/index.tsx, examples/mini-program-example/src/pages/api/basics/system/index.tsx, examples/mini-program-example/src/pages/api/device/deviceOrientation/index.tsx, examples/mini-program-example/src/pages/api/framework/index.tsx, examples/mini-program-example/src/pages/api/interface/interaction/index.tsx, examples/mini-program-example/src/pages/api/interface/navigationBar/index.tsx, examples/mini-program-example/src/pages/api/location/index.tsx, examples/mini-program-example/src/pages/api/routing/index.tsx, examples/mini-program-example/src/pages/component/cover-image/cover-image.js, examples/mini-program-example/src/pages/component/cover-view/cover-view.js
=> feat：完善了一期部分已有的api case，新增了二期部分api case

examples/mini-program-example/src/pages/component/editor/editor.tsx, packages/taro-components-mpharmony/src/components/editor/editor.tsx, packages/taro-components-mpharmony/src/components/label/label.tsx, packages/taro-mpharmony/src/api/media/EditorContext.ts
1. 修复Label控件未正确识别checked属性初始化问题
2. 例子程序中Editor控件支持format等不同格式化参数
=> Release 3.6.8 app editor zcy

packages/taro-mpharmony/src/api/base/system.ts
=> fit: 获取设备信息

examples/mini-program-example/src/app.config.ts, examples/mini-program-example/src/pages/component/index/index.tsx, examples/mini-program-example/src/pages/component/share-element/share-element.config.ts, examples/mini-program-example/src/pages/component/share-element/share-element.scss, examples/mini-program-example/src/pages/component/share-element/share-element.tsx
=> fix: 添加shareelement 例子

examples/mini-program-example/src/pages/api/basics/system/index.tsx, examples/mini-program-example/src/pages/api/openAPIS/login/index.tsx, packages/taro-mpharmony/src/api/base/system.ts, packages/taro-mpharmony/src/api/open-api/login/login.ts
=> fix: 部分接口修改为桥接native

examples/mini-program-example/src/pages/api/interface/animation/index.tsx, examples/mini-program-example/src/pages/api/interface/scroll/index.tsx, examples/mini-program-example/src/pages/api/interface/tabBar/index.tsx
在mini-program-example中增加tarBar/pageScrollTo/Animation接口的测试用例
=> feat: 增加tarBar/pageScrollTo/Animation的example case

examples/mini-program-example/src/pages/api/cache/index.tsx, examples/mini-program-example/src/pages/api/media/image/index.tsx
=> commit 完善taro example

examples/mini-program-example/src/pages/api/media/image/index.tsx, packages/taro-mpharmony/src/api/media/image/chooseImage.ts, packages/taro-mpharmony/src/api/media/image/compressImage.ts, packages/taro-mpharmony/src/api/media/image/getImageInfo.ts, packages/taro-mpharmony/src/api/media/image/saveImageToPhotosAlbum.ts
规范媒体-图片的实现，补充媒体-图片的playground示例
代码风格更新(Code style update)
鸿蒙（harmony）
=> feat: 补齐媒体-图片的接口和playgroung范例

examples/mini-program-example/src/pages/api/basics/basics/index.tsx, examples/mini-program-example/src/pages/api/basics/miniProgram/applicationLevelEvents/index.tsx, examples/mini-program-example/src/pages/api/basics/system/index.tsx, packages/taro-mpharmony/src/api/base/system.ts, packages/taro-mpharmony/src/api/ui/interaction/modal.ts
feat: 增加部分basics的example case
fix: 部分接口修改为桥接native，修改showModal样式
=> fix: 部分接口修改为桥接native，修改showModal样式

packages/taro-mpharmony/src/api/device/bluetooth/closeBluetoothAdapter.ts, packages/taro-mpharmony/src/api/device/bluetooth/getBluetoothAdapterState.ts, packages/taro-mpharmony/src/api/device/bluetooth/getBluetoothDevices.ts, packages/taro-mpharmony/src/api/device/bluetooth/getConnectedBluetoothDevices.ts, packages/taro-mpharmony/src/api/device/bluetooth/index.ts, packages/taro-mpharmony/src/api/device/bluetooth/offBluetoothAdapterStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth/offBluetoothDeviceFound.ts, packages/taro-mpharmony/src/api/device/bluetooth/openBluetoothAdapter.ts, packages/taro-mpharmony/src/api/device/bluetooth/startBluetoothDevicesDiscovery.ts, packages/taro-mpharmony/src/api/device/bluetooth/stopBluetoothDevicesDiscovery.ts
=> fix: 修改通用蓝牙相关接口实现

examples/mini-program-example/src/pages/api/media/audio/index.config.ts, examples/mini-program-example/src/pages/api/media/audio/index.tsx, examples/mini-program-example/src/pages/api/media/backgroundAudio/index.config.ts, examples/mini-program-example/src/pages/api/media/backgroundAudio/index.tsx, examples/mini-program-example/src/pages/api/media/camera/index.config.ts, examples/mini-program-example/src/pages/api/media/camera/index.tsx, examples/mini-program-example/src/pages/api/media/recording/index.config.ts, examples/mini-program-example/src/pages/api/media/recording/index.tsx, examples/mini-program-example/src/pages/api/media/richText/index.config.ts, examples/mini-program-example/src/pages/api/media/richText/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.config.ts, examples/mini-program-example/src/pages/api/media/video/index.scss, examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-mpharmony/src/api/media/audio/InnerAudioContext.ts, packages/taro-mpharmony/src/api/media/background-audio/BackgroundAudioManager.ts, packages/taro-mpharmony/src/api/media/video/chooseMedia.ts, packages/taro-mpharmony/src/api/media/video/chooseVideo.ts, packages/taro-mpharmony/src/api/media/video/compressVideo.ts, packages/taro-mpharmony/src/api/media/video/getVideoInfo.ts, packages/taro-mpharmony/src/api/media/video/openVideoEditor.ts, packages/taro-mpharmony/src/api/media/video/saveVideoToPhotosAlbum.ts
补齐媒体中场景化API支持的接口和playgroung范例
fix 修改playground测试接口
鸿蒙（harmony）
=> feat: 补齐媒体中场景化API支持的接口和playgroung范例

examples/mini-program-example/src/pages/api/interface/interaction/index.tsx, examples/mini-program-example/src/pages/api/interface/windows/index.tsx
1. 增加showActionSheet接口范例
2. 增加onWindowResize和offWindowResize接口范例
=> feat: 增加窗口API接口范例

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts
=> 更改三方件导入路径，遍历modules寻找路口文件

packages/taro-cli-convertor/src/util/index.ts, packages/taro-transformer-wx/package.json, packages/taro-transformer-wx/src/index.ts
修复了路径处理策略的冲突和变量的冲突
在transformer-wx中引入了commonJS to es6的转换插件，处理导入的三方件的导出格式
=> fix: 修复冲突，引入commonJS to es6转换插件

examples/mini-program-example/src/pages/api/device/bluetoothGeneral/index.tsx, examples/mini-program-example/src/pages/api/device/bluetoothLowCenter/index.tsx, packages/taro-mpharmony/src/api/device/bluetooth-ble/closeBLEConnection.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/createBLEConnection.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/getBLEDeviceCharacteristics.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/getBLEDeviceRSSI.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/getBLEDeviceServices.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/notifyBLECharacteristicValueChange.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/onBLECharacteristicValueChange.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/onBLEConnectionStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/readBLECharacteristicValue.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/setBLEMTU.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/writeBLECharacteristicValue.ts, packages/taro-mpharmony/src/api/device/bluetooth/getConnectedBluetoothDevices.ts
=> fix: 修改蓝牙低功耗中心设备桥接实现及相关example测试样例

examples/mini-program-example/src/util/util.ts
=> 添加两个TestConsole方法

examples/mini-program-example/src/pages/api/cache/index.tsx, examples/mini-program-example/src/pages/api/device/bluetoothGeneral/index.tsx, examples/mini-program-example/src/pages/api/device/bluetoothLowCenter/index.tsx, examples/mini-program-example/src/pages/api/device/wifi/index.tsx, examples/mini-program-example/src/pages/api/media/audio/index.tsx, examples/mini-program-example/src/pages/api/media/backgroundAudio/index.tsx, examples/mini-program-example/src/pages/api/media/camera/index.tsx, examples/mini-program-example/src/pages/api/media/image/index.tsx, examples/mini-program-example/src/pages/api/media/recording/index.tsx, examples/mini-program-example/src/pages/api/media/richText/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx, examples/mini-program-example/src/pages/api/routing/index.tsx, examples/mini-program-example/src/util/util.ts
修改媒体，数据缓存，路由的日志打印，修改数据缓存，路由的playground接口示例
错误修复
鸿蒙（harmony）
=> fix: 修改媒体，数据缓存，路由的日志打印，修改数据缓存，路由的playground接口示例

packages/taro-transformer-wx/__tests__/base.spec.ts, packages/taro-transformer-wx/__tests__/utils.ts, packages/taro-transformer-wx/package.json
=> fix: async/await转换的单元测试用例

examples/mini-program-example/src/app.config.ts, examples/mini-program-example/src/pages/api/index/index.tsx, examples/mini-program-example/src/pages/api/interface/tabBar/index.scss, examples/mini-program-example/src/pages/api/interface/tabBar/index.tsx
=> feat: 将tabBar页显示到api页中方便测试

examples/mini-program-example/src/pages/api/device/bettery/index.tsx, examples/mini-program-example/src/pages/api/device/calendar/index.tsx, examples/mini-program-example/src/pages/api/device/clipBoard/index.tsx, examples/mini-program-example/src/pages/api/device/contact/index.tsx, examples/mini-program-example/src/pages/api/device/wifi/index.tsx, packages/taro-mpharmony/src/api/device/contact/addPhoneContact.ts, packages/taro-mpharmony/src/api/device/wifi/connectWifi.ts, packages/taro-mpharmony/src/api/device/wifi/getConnectedWifi.ts, packages/taro-mpharmony/src/api/device/wifi/getWifiList.ts, packages/taro-mpharmony/src/api/device/wifi/offGetWifiList.ts, packages/taro-mpharmony/src/api/device/wifi/offWifiConnected.ts, packages/taro-mpharmony/src/api/device/wifi/offWifiConnectedWithPartialInfo.ts, packages/taro-mpharmony/src/api/device/wifi/onGetWifiList.ts, packages/taro-mpharmony/src/api/device/wifi/onWifiConnected.ts, packages/taro-mpharmony/src/api/device/wifi/onWifiConnectedWithPartialInfo.ts, packages/taro-mpharmony/src/api/device/wifi/startWifi.ts, packages/taro-mpharmony/src/api/device/wifi/stopWifi.ts
Wifi、联系人、剪贴板、电量、日历模块example样例修改及相关api桥接问题修复
=> fix: Wifi、联系人、剪贴板、电量、日历模块example样例修改及相关api桥接问题修复

packages/taro-mpharmony/src/api/device/bluetooth/offBluetoothAdapterStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth/offBluetoothDeviceFound.ts, packages/taro-mpharmony/src/api/device/bluetooth/onBluetoothAdapterStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth/onBluetoothDeviceFound.ts, packages/taro-mpharmony/src/utils/handler.ts
=> fix: utils修改及蓝牙通用部分接口返回值修改

examples/mini-program-example/src/pages/api/device/gyroscope/index.tsx, packages/taro-mpharmony/src/api/device/gyroscope/onGyroscopeChange.ts, packages/taro-mpharmony/src/api/device/gyroscope/startGyroscope.ts, packages/taro-mpharmony/src/api/device/gyroscope/stopGyroscope.ts, packages/taro-mpharmony/src/api/media/audio/InnerAudioContext.ts
修复InnerAudioContext的destory接口报错
fix
鸿蒙（harmony）
=> fix: 修改InnerAudioContext的destory接口

examples/mini-program-example/src/pages/api/file/index.tsx, packages/taro-mpharmony/src/api/files/getFileInfo.ts, packages/taro-mpharmony/src/api/files/getSavedFileInfo.ts, packages/taro-mpharmony/src/api/files/getSavedFileList.ts, packages/taro-mpharmony/src/api/files/openDocument.ts, packages/taro-mpharmony/src/api/files/removeSavedFile.ts, packages/taro-mpharmony/src/api/files/saveFile.ts
修改文件的api实现和playground示例
fix
鸿蒙（harmony）
=> fix: 修改文件的api实现和playground示例

examples/mini-program-example/src/pages/api/device/phoneCall/index.tsx, examples/mini-program-example/src/pages/api/device/vibration/index.tsx, packages/taro-mpharmony/src/api/device/bluetooth/startBluetoothDevicesDiscovery.ts, packages/taro-mpharmony/src/api/device/phone/phone.ts, packages/taro-mpharmony/src/api/device/vibrate.ts
=> fix: 修改蓝牙、电话、震动桥接实现和相关example样例

examples/mini-program-example/src/pages/api/file/index.tsx
=> fix: 修改文件的引入

examples/mini-program-example/src/pages/api/basics/basics/index.tsx, examples/mini-program-example/src/pages/api/basics/miniProgram/applicationLevelEvents/index.tsx, examples/mini-program-example/src/pages/api/basics/system/index.tsx, examples/mini-program-example/src/pages/api/canvas/index.tsx, examples/mini-program-example/src/pages/api/device/compass/index.tsx, examples/mini-program-example/src/pages/api/device/gyroscope/index.tsx, examples/mini-program-example/src/pages/api/device/keyboard/index.tsx, examples/mini-program-example/src/pages/api/device/network/index.tsx, examples/mini-program-example/src/pages/api/device/phoneCall/index.tsx, examples/mini-program-example/src/pages/api/device/screen/index.tsx, examples/mini-program-example/src/pages/api/interface/animation/index.tsx, examples/mini-program-example/src/pages/api/interface/font/index.tsx, examples/mini-program-example/src/pages/api/interface/scroll/index.tsx, examples/mini-program-example/src/pages/api/interface/windows/index.tsx, examples/mini-program-example/src/pages/component/grid-view/demo1.tsx, examples/mini-program-example/src/pages/component/grid-view/demo2.tsx, examples/mini-program-example/src/pages/component/grid-view/grid-tile.tsx, examples/mini-program-example/src/pages/component/grid-view/grid-view.tsx, examples/mini-program-example/src/pages/index/index.tsx, packages/taro-mpharmony/src/api/ui/animation/index.ts
- 优化mini-program-example中界面api的测试demo
- 修复taro-mpharmony中skew/skewX/skewY方法
=> Fix：优化mini-program-example中界面API的测试demo

packages/taro-mpharmony/src/api/location/getLocation.ts, packages/taro-mpharmony/src/api/location/offLocationChange.ts, packages/taro-mpharmony/src/api/location/offLocationChangeError.ts, packages/taro-mpharmony/src/api/location/onLocationChange.ts, packages/taro-mpharmony/src/api/location/onLocationChangeError.ts, packages/taro-mpharmony/src/api/location/startLocationUpdate.ts, packages/taro-mpharmony/src/api/location/startLocationUpdateBackground.ts, packages/taro-mpharmony/src/api/location/stopLocationUpdate.ts
=> fix: location相关API出入参问题修改

examples/mini-program-example/src/pages/api/basics/system/index.tsx, packages/taro-mpharmony/src/api/base/system.ts
=> fix: system相关API异步改同步及出参问题修改

examples/mini-program-example/src/pages/api/location/index.tsx
=> fix: location样例修改

examples/mini-program-example/src/components/buttonList/index.tsx, examples/mini-program-example/src/components/callbackContents/index.tsx, examples/mini-program-example/src/pages/api/device/contact/index.tsx
=> fix: 修复console内容

packages/taro-mpharmony/src/api/device/bluetooth/closeBluetoothAdapter.ts, packages/taro-mpharmony/src/api/device/bluetooth/getBluetoothAdapterState.ts, packages/taro-mpharmony/src/api/device/bluetooth/getBluetoothDevices.ts, packages/taro-mpharmony/src/api/device/bluetooth/openBluetoothAdapter.ts, packages/taro-mpharmony/src/api/device/bluetooth/stopBluetoothDevicesDiscovery.ts
=> fix: 通用蓝牙接口桥接出入参修改

examples/mini-program-example/src/app.scss, examples/mini-program-example/src/components/buttonList/index.scss, examples/mini-program-example/src/components/buttonList/index.tsx
=> fix: 修改了textarea resize问题,优化button点击样式,添加二级菜单点击响应

examples/mini-program-example/src/pages/api/interface/animation/index.tsx, packages/taro-mpharmony/src/api/ui/animation/index.ts
修正taro-mpharmony类型下Taro.Animation方法的行为，使其表现跟微信小程序中的一致
=> fix: 修复Animation动画行为跟微信小程序一致

examples/mini-program-example/src/pages/api/interface/font/index.tsx
=> fix: 优化loadFontFace的测试用例

examples/mini-program-example/src/pages/api/device/bluetoothLowCenter/index.tsx, packages/taro-mpharmony/src/api/device/bluetooth-ble/setBLEMTU.ts
=> fix: 蓝牙低功耗中心设备桥接出入参修改及example样例修改

examples/mini-program-example/.eslintrc, examples/mini-program-example/src/pages/api/device/bluetoothLowCenter/index.tsx, examples/mini-program-example/src/pages/api/interface/pullDownRefresh/index.config.ts, examples/mini-program-example/src/pages/api/interface/pullDownRefresh/index.tsx, examples/mini-program-example/src/pages/component/text/text.js
=> fix: 优化下拉刷新测试用例

examples/mini-program-example/src/pages/api/device/wifi/index.tsx, packages/taro-mpharmony/src/api/device/wifi/getConnectedWifi.ts, packages/taro-mpharmony/src/api/device/wifi/getWifiList.ts, packages/taro-mpharmony/src/api/device/wifi/offGetWifiList.ts, packages/taro-mpharmony/src/api/device/wifi/offWifiConnected.ts, packages/taro-mpharmony/src/api/device/wifi/startWifi.ts, packages/taro-mpharmony/src/api/device/wifi/stopWifi.ts
=> fix: 设备-wifi模块API问题修复及样例修改

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/astConvert.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taro-transformer-wx/.eslintrc.js, packages/taro-transformer-wx/__tests__/base.spec.ts, packages/taro-transformer-wx/__tests__/utils.ts, packages/taro-transformer-wx/src/adapter.ts, packages/taro-transformer-wx/src/class-method-renamer.ts, packages/taro-transformer-wx/src/class.ts, packages/taro-transformer-wx/src/constant.ts, packages/taro-transformer-wx/src/create-html-element.ts, packages/taro-transformer-wx/src/eslint.ts, packages/taro-transformer-wx/src/functional.ts, packages/taro-transformer-wx/src/index.ts, packages/taro-transformer-wx/src/interface.d.ts, packages/taro-transformer-wx/src/jsx.ts, packages/taro-transformer-wx/src/lifecycle.ts, packages/taro-transformer-wx/src/options.ts, packages/taro-transformer-wx/src/plugins.ts, packages/taro-transformer-wx/src/plugins/remove-dead-code.js, packages/taro-transformer-wx/src/render-props.ts, packages/taro-transformer-wx/src/render.ts, packages/taro-transformer-wx/src/utils.ts
fix: 修复taro convertor格式问题，包含taro-cli-convertor、taroize、taro-transformer-wx三个模块
=> fix: 修复taro convertor格式问题

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts
适配微信小程序根目录新增convert.config.json时，对key为external的value进行保存并转化为绝对路径，此路径正则匹配到的路径文件在被导入时将不会被转换
=> fix: 适配convert.config.json，对符合json内路径的文件，在其被导入时不做转换

examples/mini-program-example/src/pages/api/media/image/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-components-mpharmony/rollup.config.mjs, packages/taro-components/package.json, packages/taro-mpharmony/src/api/files/getSavedFileList.ts, packages/taro-mpharmony/src/api/media/image/chooseImage.ts, packages/taro-mpharmony/src/api/media/video/chooseMedia.ts, packages/taro-mpharmony/src/api/media/video/chooseVideo.ts, packages/taro-mpharmony/src/api/media/video/compressVideo.ts, packages/taro-mpharmony/src/api/media/video/getVideoInfo.ts, packages/taro-mpharmony/src/api/media/video/openVideoEditor.ts, packages/taro-mpharmony/src/api/media/video/saveVideoToPhotosAlbum.ts, packages/taro-rn/src/lib/index.ts
修改Windows系统差异性问题，增加Api入参的判断
fix
鸿蒙（harmony）
=> fix: 修改Windows系统差异性问题，增加Api入参的判断

examples/mini-program-example/src/pages/api/network/webSocket/index.tsx, packages/taro-mpharmony/src/api/network/websocket/index.ts
=> fix: 修正websocket接口并优化测试用例

examples/mini-program-example/package.json
=> 修改@babel/runtime版本

examples/mini-program-example/src/pages/api/device/clipBoard/index.tsx, examples/mini-program-example/src/pages/api/device/keyboard/index.tsx, examples/mini-program-example/src/pages/api/device/screen/index.tsx, packages/taro-mpharmony/src/api/device/keyBoard/hideKeyboard.ts, packages/taro-mpharmony/src/api/device/keyBoard/offKeyboardHeightChange.ts, packages/taro-mpharmony/src/api/device/keyBoard/onKeyboardHeightChange.ts, packages/taro-mpharmony/src/api/device/screen/getScreenBrightness.ts, packages/taro-mpharmony/src/api/device/screen/offUserCaptureScreen.ts, packages/taro-mpharmony/src/api/device/screen/onUserCaptureScreen.ts, packages/taro-mpharmony/src/api/device/screen/setKeepScreenOn.ts, packages/taro-mpharmony/src/api/device/screen/setScreenBrightness.ts, packages/taro-mpharmony/src/utils/callbakMap.ts
=> fix: 屏幕、剪贴板、键盘模块API桥接修改

examples/mini-program-example/src/components/callbackContents/index.tsx
=> fix: 修复了callback挂载stringify中循环引用的问题

packages/taro-mpharmony/src/api/base/index.ts
=> fix: 修改返回值跟微信小程序一致

packages/taro-cli-convertor/src/util/index.ts
修改require语句的组件路径的处理方式，能够处理js文件不加后缀的引入
=> fix: 修改require语句的组件路径的处理方式，能够处理js文件不加后缀的引入

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts
对于引用的三方库，转换时默认从node_modules中搜索并转换，同时支持用户在convert.config.json中配置搜索路径
=> feat: 支持用户自定义三方库搜索目录

examples/mini-program-example/package.json
=> feat: 添加了rebuild package的脚本，方便桥接重编译

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts
将三方库复制功能合并到接口handleThirdPartyLib
=> fix: 将三方库复制合并到handleThirdPartyLib

examples/mini-program-example/src/pages/api/media/audio/index.tsx
修改innerAudioContext的可测试行问题
fix
鸿蒙（harmony）
=> fix: 修改innerAudioContext的可测试行问题

examples/mini-program-example/src/pages/api/interface/interaction/index.tsx
=> fix: 优化toast和loading测试用例

packages/taro-cli-convertor/src/util/index.ts
=> fix: 纯js三方库转换时，支持pnpm的link文件夹复制

examples/mini-program-example/src/app.ts, examples/mini-program-example/src/pages/api/device/keyboard/index.tsx, examples/mini-program-example/src/pages/api/framework/index.config.ts, examples/mini-program-example/src/pages/api/framework/index.tsx, examples/mini-program-example/src/pages/api/index/index.tsx, examples/mini-program-example/src/pages/api/interface/interaction/index.tsx, examples/mini-program-example/src/pages/api/media/image/index.tsx, examples/mini-program-example/src/pages/api/media/richText/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx
=> fix: 增加App/Page生命周期测试用例

packages/taro-cli-convertor/src/util/index.ts
fix: 修复文件夹中的子文件夹为symbolicLink时转换异常
=> fix: 修复文件夹中的子文件夹为symbolicLink时转换异常

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts
1、优化支持可配置不转换目录
2、增加三方库和不转换目录复制时的控制台日志
=> fix: 优化支持可配置不转换目录

examples/mini-program-example/src/app.config.ts, examples/mini-program-example/src/pages/api/interface/tabBar/index.tsx, examples/mini-program-example/src/pages/api/routing/index.tsx, examples/mini-program-example/src/pages/api/routing/routeA/index.config.ts, examples/mini-program-example/src/pages/api/routing/routeA/index.tsx, examples/mini-program-example/src/pages/api/taro/expand/index.tsx
- 优化navigateBack，setTabBarBadge测试用例
- 增加getEnv测试用例
=> fix: 优化navigateBack/setTabBarBadge/getEnv的可测试性

examples/mini-program-example/src/pages/api/device/accelerometer/index.tsx, examples/mini-program-example/src/pages/api/device/bettery/index.tsx, examples/mini-program-example/src/pages/api/device/clipBoard/index.tsx, examples/mini-program-example/src/pages/api/device/compass/index.tsx, examples/mini-program-example/src/pages/api/device/keyboard/index.tsx, examples/mini-program-example/src/pages/api/device/network/index.tsx, examples/mini-program-example/src/pages/api/device/screen/index.tsx, packages/taro-mpharmony/src/api/device/accelerometer/offAccelerometerChange.ts, packages/taro-mpharmony/src/api/device/accelerometer/onAccelerometerChange.ts, packages/taro-mpharmony/src/api/device/accelerometer/startAccelerometer.ts, packages/taro-mpharmony/src/api/device/accelerometer/stopAccelerometer.ts, packages/taro-mpharmony/src/api/device/compass/offCompassChange.ts, packages/taro-mpharmony/src/api/device/compass/onCompassChange.ts, packages/taro-mpharmony/src/api/device/compass/startCompass.ts, packages/taro-mpharmony/src/api/device/compass/stopCompass.ts, packages/taro-mpharmony/src/api/device/network.ts
设备模块加速计、罗盘、网络API修改，example样例修改.
=> fix: 设备模块加速计、罗盘、网络API修改，example样例修改.

examples/mini-program-example/src/app.ts, examples/mini-program-example/src/pages/api/framework/index.tsx
=> fix: 增加页面显示和隐藏的生命周期测试用例

packages/taroize/src/wxml.ts
=> fix: 修改taroize源码中对slot属性的判断条件，新增当slot为空串时去除slot属性

examples/mini-program-example/src/pages/api/media/audio/index.tsx, examples/mini-program-example/src/pages/api/media/backgroundAudio/index.tsx, examples/mini-program-example/src/pages/api/media/richText/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-mpharmony/src/api/media/EditorContext.ts
补齐editorContext的blur和insertDivider接口，修改innerAudioContext的样例
fix
鸿蒙（harmony）
=> fix: 补齐editorContext的blur和insertDivider接口，修改innerAudioContext的样例

packages/taro-mpharmony/src/api/base/caniuse.ts, packages/taro-mpharmony/src/api/base/index.ts
=> fix: 修改canIUse API

packages/taroize/src/wxml.ts
=> fix: 优化slot为空串时移除slot属性这部分的代码

packages/taro-router-rn/package.json, packages/taro-router-rn/src/view/tabBarUtils.ts, pnpm-lock.yaml
=> fix: 解决taro-router-rn编译错误

examples/mini-program-example/src/app.ts, examples/mini-program-example/src/pages/api/network/download/index.tsx, examples/mini-program-example/src/pages/api/network/request/index.tsx, examples/mini-program-example/src/pages/api/network/upload/index.tsx, packages/taro-mpharmony/src/api/network/download.ts, packages/taro-mpharmony/src/api/network/request/index.ts, packages/taro-mpharmony/src/api/network/upload.ts
=> fix: 完善网络请求API和测试用例

packages/taro-plugin-html/src/index.ts
fix: 解决taro-plugin-html编译时类型报错问题
- [x ] 错误修复(Bugfix) issue: fix #
=> fix: 解决taro-plugin-html编译时类型报错问题

packages/taro-cli/templates/default/package.json.tmpl
fix: 修复packages.json.tmpl文件中出现的语法问题
=> fix: 修复packages.json.tmpl文件中出现的语法问题

packages/taro-cli-convertor/src/index.ts
=> fix: 将this.data.xx=XX的语句转换/合并为setData语法

packages/taro-components/src/components/canvas/canvas.tsx, packages/taro-components/src/components/canvas/readme.md
=> fix: canvas H5显示拉伸问题

examples/mini-program-example/src/pages/api/basics/debug/index.tsx, examples/mini-program-example/src/pages/api/basics/update/index.tsx, examples/mini-program-example/src/pages/api/device/memory/index.tsx, examples/mini-program-example/src/pages/api/taro/expand/index.tsx, packages/taro-mpharmony/src/api/base/debug.ts, packages/taro-mpharmony/src/api/base/debug/getLogManager.ts, packages/taro-mpharmony/src/api/base/debug/getRealtimeLogManager.ts, packages/taro-mpharmony/src/api/base/debug/index.ts, packages/taro-mpharmony/src/api/base/debug/setEnableDebug.ts, packages/taro-mpharmony/src/api/base/index.ts, packages/taro-mpharmony/src/api/base/system.ts, packages/taro-mpharmony/src/api/base/update.ts, packages/taro-mpharmony/src/api/base/update/getUpdateManager.ts, packages/taro-mpharmony/src/api/base/update/index.ts, packages/taro-mpharmony/src/api/device/memory/onMemoryWarning.ts, packages/taro-mpharmony/src/api/taro.ts
=> fix: 部分API使用空实现并补充对应测试用例

examples/mini-program-example/src/pages/api/analysis/index.tsx, examples/mini-program-example/src/pages/api/file/index.tsx, examples/mini-program-example/src/pages/api/media/audio/index.tsx, packages/taro-mpharmony/src/api/data-analysis/getExptInfoSync.ts, packages/taro-mpharmony/src/api/data-analysis/index.ts, packages/taro-mpharmony/src/api/data-analysis/reportAnalytics.ts, packages/taro-mpharmony/src/api/media/audio/AudioContext.ts, packages/taro-mpharmony/src/api/media/audio/index.ts
增加createAudioContext等接口的实现，补齐playground的样例
fix
鸿蒙（harmony）
=> fix: 增加createAudioContext等接口的实现，补齐playground的样例

examples/mini-program-example/src/pages/api/wxml/index.tsx, packages/taro-components-mpharmony/src/components/scroll-view/index.tsx, packages/taro-mpharmony/src/api/wxml/selectorQuery.ts
=> fix: 修复wxml测试用例

packages/taro-components-mpharmony/src/components/sticky-section/sticky-section.tsx
=> fix: 解决编译错误

packages/taro-cli-convertor/src/index.ts
如果源工程存在tsconfig.json，转换后拷贝到工程根目录下。
=> fix: 拷贝tsconfig.json到转换后工程

packages/taro-mpharmony/src/api/ui/fonts.ts
=> fix: loadFontFace返回的回调对象增加status属性

packages/taro-cli-convertor/src/util/index.ts
=> fix: 修复以/开头文件导入时找不到文件

.github/workflows/code-check.yml, packages/taro-mpharmony/src/api/device/compass/onCompassChange.ts, packages/taro-mpharmony/src/api/device/screen/onUserCaptureScreen.ts
=> CI增加代码规范性检查(ESlint)

packages/taro-cli-convertor/src/index.ts
修复问题，之前过滤条件在前面，导致一些三方库被过滤掉了没有走后面的拷贝流程。
=> fix: 修复部分三方库会被过滤掉未拷贝的问题

examples/mini-program-example/src/index.html, examples/mini-program-example/src/pages/api/basics/debug/index.tsx, examples/mini-program-example/src/pages/api/basics/update/index.tsx, examples/mini-program-example/src/pages/api/device/memory/index.tsx, examples/mini-program-example/src/pages/api/interface/navigationBar/index.tsx, examples/mini-program-example/src/pages/api/taro/expand/index.tsx, packages/taro-mpharmony/src/api/ui/navigation-bar/index.ts
=> fix: 修复导航栏相关API以及补充测试用例

packages/taro-cli-convertor/src/index.ts
=> fix: 修复小驼峰命名自定义组件报错问题

packages/taro-transformer-wx/src/index.ts, packages/taroize/package.json, packages/taroize/src/script.ts, packages/taroize/src/utils.ts, pnpm-lock.yaml
将commonjs的导入导出转换为es6的语法，支持commonjs和es6的导入导出混用
=> feat: 支持commonjs和es6的导入导出混用

examples/mini-program-example/src/pages/api/location/index.tsx, packages/taro-mpharmony/src/api/location/chooseLocation.ts, packages/taro-mpharmony/src/api/location/getFuzzyLocation.ts, packages/taro-mpharmony/src/api/location/getLocation.ts, packages/taro-mpharmony/src/api/location/index.ts, packages/taro-mpharmony/src/api/location/openLocation.ts, packages/taro-mpharmony/src/api/location/style.scss, packages/taro-mpharmony/src/utils/coordinateConvert.ts
=> fix: 位置模块接口实现问题及样例修改

examples/mini-program-example/src/pages/api/canvas/index.scss, examples/mini-program-example/src/pages/api/canvas/index.tsx, packages/taro-mpharmony/src/api/canvas/CanvasContext.ts
fix: 修改canvasContext的createPattern、setFontSize等方法实现，补齐playground的样例
=> fix: 修改canvasContext的createPattern、setFontSize等方法实现，补齐playground的样例

examples/mini-program-example/src/app.ts, examples/mini-program-example/src/pages/api/basics/miniProgram/lifeCycle/index.tsx, examples/mini-program-example/src/pages/api/interface/menu/index.tsx, examples/mini-program-example/src/pages/api/interface/navigationBar/index.tsx, examples/mini-program-example/src/pages/api/redirection/index.tsx, packages/taro-mpharmony/src/api/base/weapp/life-cycle.ts, packages/taro-mpharmony/src/api/navigate/index.ts, packages/taro-mpharmony/src/api/ui/menu.ts
=> fix: 实现跳转小程序、获取启动参数、菜单位置API

packages/taro-with-weapp/src/index.ts
=> fix: 修正@withWeapp的componentMethodsProxy实现

packages/taro-mpharmony/src/api/device/memory/offMemoryWarning.ts, packages/taro-mpharmony/src/api/device/memory/onMemoryWarning.ts
=> fix: 修改内存告警接口实现

examples/mini-program-example/src/pages/api/openAPIS/login/index.tsx, packages/taro-mpharmony/src/api/open-api/login/login.ts
=> fix: 修复login接口以及优化测试用例

examples/mini-program-example/src/pages/api/file/index.tsx, packages/taro-mpharmony/src/api/media/video/chooseMedia.ts
修改chooseMedia出参的处理
fix
鸿蒙（harmony）
=> fix: 修改chooseMedia出参的处理

examples/mini-program-example/src/pages/api/basics/performance/index.tsx, packages/taro-mpharmony/src/api/base/performance.ts, packages/taro-mpharmony/src/api/device/accelerometer/startAccelerometer.ts, packages/taro-mpharmony/src/api/device/memory/offMemoryWarning.ts, packages/taro-mpharmony/src/api/device/memory/onMemoryWarning.ts
=> fix: 设备、基础模块接口实现及样例修改。

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taroize/src/index.ts, packages/taroize/src/script.ts, packages/taroize/src/template.ts, packages/taroize/src/wxml.ts
fix: 修复当使用工具函数init页面时向withWeapp传入{}问题
=> fix: 修复当使用工具函数init页面时向withWeapp传入{}问题

examples/mini-program-example/src/pages/api/media/video/index.tsx
fix：修改了media api中video的compressVideo按钮禁用问题
=> fix：修改了media api中video的compressVideo按钮禁用问题

packages/taro-with-weapp/src/index.ts
修复 @withWeapp 不支持behaviors.lifetime属性
=> 修复 @withWeapp 不支持behaviors.lifetime属性

packages/taro-transformer-wx/src/wxs.ts, packages/taro-with-weapp/src/index.ts, packages/taroize/src/wxml.ts
=> fix: 修复正则表达式转换不一致问题

packages/taro-with-weapp/src/index.ts, packages/taroize/src/wxml.ts
wxml的px/rpx转为rem。原数据<1的转成1rem。
=> fix: wxml的px/rpx转为rem

packages/taro-with-weapp/package.json
=> feat: taro-with-weapp添加lint和format脚本

packages/taro-transformer-wx/src/index.ts
修复commonjs导出对象转换后运行异常
module.exports = {addNum3, addNum4}
转换为
export {addNum3, addNum4}
=> fix: 修复commonjs导出对象转换后运行异常

packages/taro-cli-convertor/src/index.ts
修复不转换的目录搬迁路径:copy到src里面（之前在src外层）
=> fix: 修复不转换的目录搬迁路径:copy到src里面

packages/taro-cli-convertor/src/index.ts
=> fix: 处理不转换的页面路径修改:放到src里面

examples/mini-program-example/config/index.js
=> fix:修复mini-program-example下build后dist下多node_modules文件问题

examples/mini-program-example/src/pages/api/cloudServices/index.tsx, packages/taro-mpharmony/src/api/base/system.ts, packages/taro-mpharmony/src/api/cloud/index.ts
fix: 修复系统模块API获取系统及设备相关信息错误问题以及云开发接口和样例补充
=> fix: 修复系统模块API获取系统及设备相关信息错误问题以及云开发接口和样例补充

packages/taroize/src/template.ts
=> fix: 修复文件转换中不支持绝对路径的转换问题

packages/taro-mpharmony/src/index.ts
=> 在JS侧，添加原生Api调用的日志

packages/taro-components/src/components/image/image.tsx
=> Image组件兼容mode=""和src无值的情况

packages/taroize/src/wxml.ts
修复wxml的px/rpx改为rem时未考虑原数据为0的情况
=> fix: 修复wxml的px/rpx改为rem时未考虑原数据为0的情况

examples/mini-program-example/src/pages/api/basics/performance/index.tsx, examples/mini-program-example/src/pages/api/cloudServices/index.tsx, examples/mini-program-example/src/pages/api/file/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx, examples/mini-program-example/src/pages/api/network/download/index.tsx, examples/mini-program-example/src/pages/api/network/request/index.tsx, examples/mini-program-example/src/pages/api/network/upload/index.tsx
=> fix: 补充网络相关测试样例

packages/taro-mpharmony/src/index.ts
=> 仅开发阶段输出原生Api的日志

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/astConvert.ts
根据模块类型(comonjs、es6)确定导入taro的格式
=> fix: 根据模块类型(comonjs、es6)确定导入taro的格式

examples/mini-program-example/src/pages/api/media/image/index.tsx, packages/taro-mpharmony/src/api/files/openDocument.ts, packages/taro-mpharmony/src/api/media/image/previewImage.ts, packages/taro-platform-mpharmony/package.json
修改previewImage的实现，修改previewImage样例，修改taro-platform-mpharmony的版本号
fix
鸿蒙（harmony）
=> fix: 修改previewImage的实现，修改previewImage样例，修改taro-platform-mpharmony的版本号

examples/mini-program-example/src/pages/api/media/audio/index.tsx
修复了媒体-音频中AudioContext多端音频无法自由暂停和跳转的问题
=> fix:修复了媒体-音频中AudioContext多端音频无法自由暂停和跳转的问题

packages/taro-router/src/api.ts, packages/taro/types/global.d.ts
修复Taro-路由navigateTo返回参数中缺失eventChannel
=> fix:修复Taro-路由navigateTo返回参数中缺失eventChannel

examples/mini-program-example/package.json, examples/mini-program-example/src/pages/api/canvas/index.tsx, packages/taro-mpharmony/src/api/canvas/canvasToTempFilePath.ts
=> fix: canvas能力补充及样例问题修改

packages/taro-mpharmony/src/api/location/getLocation.ts
=> fix: 高精度定位超时问题修改

examples/mini-program-example/src/pages/api/interface/menu/index.config.ts, examples/mini-program-example/src/pages/api/interface/menu/index.scss, examples/mini-program-example/src/pages/api/interface/menu/index.tsx, examples/mini-program-example/src/pages/api/media/image/index.tsx, packages/taro-mpharmony/src/index.ts, packages/taro-router/src/router/spa.ts
=> fix: 根据navigationStyle配置导航栏是否可见

packages/taroize/src/wxml.ts
修复wx:key="index"写在wx:for前面时会转换不正确的问题
=> fix: 修复wx:key="index"写在wx:for前面时会转换不正确的问题

packages/taro-cli-convertor/src/index.ts
fix: 修复this.data.xx合并进setData会打乱代码逻辑顺序的问题。
由于setData合并会导致代码顺序打乱，不再合并任何setData，直接一句this.data.xx=XX转为一句setData
=> fix: 修复this.data.xx合并进setData会打乱代码逻辑顺序的问题

packages/taro-cli-convertor/src/index.ts
=> fix: 修复生成js文件的时候抛异常阻塞后续的遍历

packages/taroize/src/wxml.ts
fix: 修复convertor解析style='{{ xxx }}'格式报错
=> fix: 修复convertor解析style='{{ xxx }}'格式报错

packages/taro-cli-convertor/src/index.ts
=> fix: 去除页面上多余的template模板导入

packages/taro-mpharmony/src/api/base/system.ts
=> fix: 修改基础-系统信息返回的SDKVersion类型

packages/taro-with-weapp/src/index.ts
=> 把properties转换为React的state，支持可读可写，同时再通过props传入修改后的值

packages/taroize/src/wxml.ts
fix: 修改wxml内单位转换的正则,并对style相关处理添加try catch, 并run format修正格式
=> fix: 修改wxml内单位转换的正则,并对style相关处理添加try catch

packages/taro-mpharmony/src/api/ui/interaction/index.ts
修改路由跳转模态框自动消失的问题
fix
鸿蒙（harmony）
=> fix: 修改路由跳转模态框自动消失的问题

examples/mini-program-example/src/pages/api/interface/menu/index.tsx, packages/taro-mpharmony/src/api/ui/navigation-bar/index.ts, packages/taro-router/src/router/page.ts, packages/taro-router/src/style.ts
=> feat: 页面增加导航栏是否隐藏样式处理

packages/taro-mpharmony/src/api/base/weapp/life-cycle.ts
=> fix: 修复getLaunchOptionsSync返回的数据内容

examples/mini-program-example/src/pages/api/wxml/index.tsx, packages/taro-mpharmony/src/api/wxml/nodesRef.ts, packages/taro-mpharmony/src/api/wxml/selectorQuery.ts
=> fix: 修复NodesRef.fields针对Canvas组件设置node/context无效的问题

examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-mpharmony/src/api/media/video/compressVideo.ts
修改媒体-视频-compressVideo无法压缩视频返回正常参数问题
=> fix:修改媒体-视频-compressVideo无法压缩视频返回正常参数问题

packages/taro-cli-convertor/src/index.ts, packages/taroize/src/wxml.ts
小程序template中使用的方法，来自调用（直接或间接）它的js界面，小程序内部实现了方法从js界面传递到template
转换后，父组件传值到子组件，统一采用了props的方式，但是转换中没有考虑template function的传递
在转换中实现template中处理事务的function通过props传递
=> fix: 实现template中处理事务的function通过props传递

packages/babel-plugin-transform-taroapi/src/index.ts
=> fix: canIUse字符串字面量传参问题处理

examples/mini-program-example/src/pages/api/wxml/index.tsx, packages/taro-mpharmony/src/api/wxml/selectorQuery.ts
=> fix: 修复nodesRef.field设置properties无效的问题

packages/taro-mpharmony/src/api/wxml/IntersectionObserver.ts
=> fix: 修改IntersectionObserver的监听反馈时间为timestamp值

packages/taroize/src/wxml.ts
修复wx:if和wx:for配合使用场景下的转换错误，按照优先级进行拆分转换
=> fix: 修复wx:if和wx:for配合使用场景下的转换错误

packages/taro-mpharmony/src/api/ui/navigation-bar/index.ts, packages/taro-router/src/router/page.ts
=> fix: 修复position:fixed定位出错的问题

packages/taro-components/src/components/button/style/index.scss, packages/taro-router/src/router/spa.ts
=> 1. 路由错误抛出原始异常，便于定位

examples/mini-program-example/src/pages/component/navigator/navigator.js, packages/taro-api/src/env.js, packages/taro-components-mpharmony/src/common/utils.ts, packages/taro/types/api/taro.extend.d.ts, packages/taro/types/global.d.ts
=> fix: getEnv增加MPHARMONY类型

packages/taro-mpharmony/src/api/ui/navigation-bar/index.ts
=> fix: 修复页面内容显示不全的问题

packages/taro-mpharmony/src/api/wxml/selectorQuery.ts, packages/taro-router/src/events/resize.ts
=> fix: 修复Page.onResize回调参数缺少的字段

packages/taro-cli-convertor/src/index.ts, packages/taroize/src/template.ts, packages/taroize/src/wxml.ts
=> fix: 适配template的动态名称转换

examples/mini-program-example/src/app.config.ts, examples/mini-program-example/src/app.ts, examples/mini-program-example/src/pages/api/redirection/index.tsx, examples/mini-program-example/src/pages/component/navigator/navigator.js, examples/mini-program-example/src/pages/error/index.config.ts, examples/mini-program-example/src/pages/error/index.scss, examples/mini-program-example/src/pages/error/index.tsx, packages/taro-mpharmony/src/api/base/weapp/life-cycle.ts, packages/taro-mpharmony/src/api/navigate/index.ts
=> fix: 修改跳转到其他应用的测试用例

packages/taro-router/src/api.ts
=> fix: 为navigateBack添加数量上限限制

packages/taro-cli-convertor/src/index.ts
=> fix: 删除没有引用的函数formatFile

examples/mini-program-example/src/components/callbackContents/index.tsx, examples/mini-program-example/src/pages/api/basics/basics/index.tsx, examples/mini-program-example/src/pages/api/cache/index.tsx, examples/mini-program-example/src/pages/api/canvas/index.tsx, examples/mini-program-example/src/pages/api/device/network/index.tsx, examples/mini-program-example/src/pages/api/device/screen/index.tsx, examples/mini-program-example/src/pages/api/file/index.tsx, examples/mini-program-example/src/pages/api/interface/animation/index.tsx, examples/mini-program-example/src/pages/api/interface/menu/index.tsx, examples/mini-program-example/src/pages/api/interface/scroll/index.tsx, examples/mini-program-example/src/pages/api/media/audio/index.tsx, examples/mini-program-example/src/pages/api/media/richText/index.tsx, examples/mini-program-example/src/pages/api/media/video/index.tsx, examples/mini-program-example/src/pages/api/network/download/index.tsx, examples/mini-program-example/src/pages/api/wxml/index.tsx
=> fix: 添加部分apicallback回调挂载

packages/taro-cli-convertor/package.json, packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/astConvert.ts, packages/taro-transformer-wx/package.json, packages/taro-transformer-wx/src/index.ts, packages/taroize/src/index.ts, packages/taroize/src/utils.ts, packages/taroize/src/wxml.ts, pnpm-lock.yaml
=> fix: 代码回退#313

packages/taro-cli-convertor/src/index.ts, packages/taroize/src/wxml.ts
=> fix: 增加data-自定义属性识别与转换

packages/taroize/src/index.ts, packages/taroize/src/script.ts
=> fix: 回退#323

examples/mini-program-example/src/pages/api/network/request/index.tsx, packages/taro-mpharmony/src/api/network/request/index.ts
=> fix: 修复request接口超时弹出错误页的问题

examples/mini-program-example/src/pages/api/media/audio/index.tsx
修改InnerAudioContext的样例，修改多实例innerAudioContext的接口没有调用的问题
fix
鸿蒙（harmony）
=> fix: 修改InnerAudioContext的样例，修改多实例innerAudioContext的接口没有调用的问题

examples/mini-program-example/src/app.ts, examples/mini-program-example/src/components/callbackContents/index.scss, examples/mini-program-example/src/pages/api/advertising/index.tsx, examples/mini-program-example/src/pages/api/framework/index.scss, examples/mini-program-example/src/pages/api/framework/index.tsx, examples/mini-program-example/src/pages/api/index/index.tsx, examples/mini-program-example/src/pages/api/taro/expand/index.tsx
=> fix: 修复生命周期与部分其他api回调挂载实现

packages/taro-mpharmony/src/api/network/request/index.ts
=> fix: request的method参数支持大小写

examples/mini-program-example/src/pages/api/routing/index.tsx, packages/taro-router/src/api.ts
fix(API): 修复redirectTo跳转到不存在页面依然反馈成功的问题
=> fix(API): 修复redirectTo跳转到不存在页面依然反馈成功的问题

packages/taro-router/src/router/page.ts
=> fix: 修复tab页面导航栏隐藏与显示情况下样式问题

examples/mini-program-example/src/pages/api/canvas/index.tsx
=> fix: 增加canvasContext中fill方法的测试场景

examples/mini-program-example/src/pages/api/canvas/index.tsx
canvasContext中quadraticCurveTo方法样例修改参数不生效问题修复
=> fix: canvasContext中quadraticCurveTo方法样例修改参数不生效问题修复

packages/taro-mpharmony/src/api/canvas/canvasToTempFilePath.ts
canvasToTempFilePath接口fileType为jpg时背景为黑色问题修改
=> fix: canvasToTempFilePath接口fileType为jpg时背景为黑色问题修改

packages/taro-cli-convertor/src/index.ts, packages/taroize/src/template.ts, packages/taroize/src/wxml.ts
添加对template的预解析，求出直接调用关系，并以此求出完整的调用关系
利用预解析，修复template同页面嵌套时方法和数据的抽取问题
=> fix: 添加对template的预解析，修复template同页面嵌套时方法和数据的抽取问题

packages/taro-mpharmony/src/api/base/index.ts
=> fix: mpharmony类型配置USER_DATA_PATH常量

examples/mini-program-example/src/pages/api/interface/navigationBar/index.config.ts, packages/taro-mpharmony/src/index.ts, packages/taro-router/src/router/spa.ts
=> fix: 修复导航栏颜色配置无效的问题

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/global.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taroize/src/global.ts, packages/taroize/src/index.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts
=> feat: 生成日志文件

packages/taro-cli-convertor/__tests__/__snapshots__/index.test.ts.snap, packages/taro-cli-convertor/__tests__/index.test.ts, packages/taro-cli-convertor/__tests__/util.ts, packages/taro-cli-convertor/src/index.ts
fix: 支持require引用为空，优化require动态引用的异常信息
// 正常场景
const aa = require('aa')
// 未考虑场景1：
const aa = require('aa' + bb)
// 未考虑场景2：
const aa = require()
=> fix: 支持require引用为空，优化require动态引用的异常信息

packages/taroize/__tests__/wxml.test.ts, packages/taroize/src/wxml.ts
fix: style动态计算转换后样式失效问题修复，以及测试用例
=> fix: style动态计算转换后样式失效问题修复

packages/taroize/__tests__/template.test.ts
=> feat: 补充template.ts的测试用例

packages/taroize/src/global.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts, packages/taroize/src/wxml.ts
/
fix: 修复template中在引用工具类时路径转换错误
=> fix: 修复template中在引用工具类时路径转换错误

packages/taro-cli-convertor/package.json, packages/taro-transformer-wx/package.json, packages/taro-with-weapp/package.json, packages/taroize/__tests__/__snapshots__/script.test.ts.snap, packages/taroize/__tests__/__snapshots__/template.test.ts.snap, packages/taroize/__tests__/__snapshots__/wxml.test.ts.snap, packages/taroize/__tests__/script.test.ts, packages/taroize/__tests__/template.test.ts, packages/taroize/__tests__/util.ts, packages/taroize/__tests__/wxml.test.ts, packages/taroize/package.json
feat: taroize包下单元测试的优化，快照文件的上传，package.json中jest指令更换
=> feat: taroize包下单元测试的优化，快照文件的上传，package.json中jest指令更换

packages/taro-cli-convertor/__tests__/__snapshots__/index.test.ts.snap, packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap, packages/taro-cli-convertor/__tests__/index.test.ts, packages/taro-cli-convertor/__tests__/script.test.ts, packages/taro-cli-convertor/package.json, packages/taro-cli-convertor/src/index.ts, packages/taroize/package.json, packages/taroize/src/global.ts, packages/taroize/src/index.ts
fix: 解决convert lab配置miniprogramRoot转换冲突问题以及优化单元测试快照
=> fix: 解决convert lab配置miniprogramRoot转换冲突问题以及优化单元测试快照

packages/taro-cli-convertor/__tests__/index.test.ts, packages/taro-cli-convertor/__tests__/script.test.ts, packages/taroize/__tests__/event.test.ts, packages/taroize/__tests__/script.test.ts, packages/taroize/__tests__/template.test.ts, packages/taroize/__tests__/wxml.test.ts, packages/taroize/src/global.ts, packages/taroize/src/index.ts
=> fix: 还原代码rootPath以及优化单元测试代码

packages/taro-mpharmony/src/api/ui/navigation-bar/index.ts, packages/taro-router/src/router/page.ts
=> fix: 修复从有导航栏跳到无导航栏页面时页面内容跳动的问题

packages/taroize/__tests__/__snapshots__/template.test.ts.snap, packages/taroize/__tests__/template.test.ts
/
补充template中在引用工具类时路径转换错误测试用例
=> feat: 补充template中在引用工具类时路径转换错误测试用例

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taro-transformer-wx/src/global.ts, packages/taro-transformer-wx/src/index.ts, packages/taro-transformer-wx/src/options.ts, packages/taro-transformer-wx/src/utils.ts, packages/taro-transformer-wx/src/wxs.ts, packages/taroize/src/script.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts, packages/taroize/src/vue.ts, packages/taroize/src/wxml.ts
fix: 日志优化，覆盖taro-cli-convertor、taroize、taro-transformer-wx模块
=> fix: 日志优化，覆盖taro-cli-convertor、taroize、taro-transformer-wx模块

packages/taro-transformer-wx/src/wxs.ts, packages/taroize/src/wxml.ts
=> fix: 解决getDate()转换后方法找不到问题

packages/taro-cli-convertor/src/index.ts
为元素或方法可能为undefined的数据添加可选链操作符
可能为undefinde：
page/组件的data属性中初始化为undefined的数据；page/组件的生命周期中声明并使用setData初始化的数据
添加可选链操作符：
xxx[xxxx] -> xxx?.[xxxx]
xxx.xxxx.xxxxx -> xxx?.xxxx?.xxxxx
=> fix: 为元素或方法可能为undefined的数据添加可选链操作符

packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap, packages/taro-cli-convertor/package.json, packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/constants.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taroize/src/constant.ts, packages/taroize/src/index.ts, packages/taroize/src/script.ts, pnpm-lock.yaml
feat: 支持转换小程序插件
1、支持小程序跳转插件页面
2、支持小程序使用插件组件
3、支持小程序调用插件模块
=> feat: 支持转换小程序插件

packages/taro-platform-mpharmony/build/definition-json/parser.ts
=> fix: 解决编译报错问题

packages/taroize/src/script.ts
=> fix: 修复微信playgroud转换报错

packages/taro-platform-mpharmony/build/definition-json/parser.ts
=> fix: 修改解析组件声明文件兼容各种系统环境换行符

packages/taro-with-weapp/src/index.ts
=> 兼容properties定义的变量没有value的情况，仅仅只是声明类型

examples/mini-program-example/src/pages/component/live-player/live-player.js, examples/mini-program-example/src/pages/component/live-player/live-player.scss, packages/taro-components/src/components/live-player/live-player.tsx, pnpm-lock.yaml
=> fix: live-player添加测试样例

packages/taroize/__tests__/__snapshots__/wxml.test.ts.snap, packages/taroize/__tests__/wxml.test.ts
=> fix: 补充wx作用域属性解析的测试用例

packages/taro-cli-convertor/__tests__/__mocks__/fs-extra.js, packages/taro-cli-convertor/__tests__/__mocks__/path.js, packages/taro-cli-convertor/__tests__/__snapshots__/convertor.test.ts.snap, packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap, packages/taro-cli-convertor/__tests__/config.test.ts, packages/taro-cli-convertor/__tests__/convertor.test.ts, packages/taro-cli-convertor/__tests__/data/fileData.ts, packages/taro-cli-convertor/__tests__/script.test.ts, packages/taro-cli-convertor/package.json, packages/taro-cli-convertor/src/index.ts, pnpm-lock.yaml
1、增加demo小程序转换的测试用例 
2、增加fs的mock文件
=> feat: 1、增加demo小程序转换的测试用例 2、增加fs的mock文件

packages/taro-with-weapp/src/index.ts
=> 兼容properties定义的变量值为null和undefined情况

packages/taroize/__tests__/__snapshots__/template.test.ts.snap, packages/taroize/__tests__/__snapshots__/wxml.test.ts.snap, packages/taroize/__tests__/template.test.ts, packages/taroize/__tests__/wxml.test.ts
=> feat: 优化taroize测试分类以及补充部分测试用例

packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap, packages/taro-cli-convertor/__tests__/config.test.ts, packages/taro-cli-convertor/__tests__/script.test.ts, packages/taro-cli-convertor/src/index.ts
- [X ] 错误修复(Bugfix) issue: fix #
- [X ] 微信小程序
=> fix: 修改programRoot的测试用例，将programRoot代码移至parseProjectConfig中

examples/mini-program-example/src/app.ts, packages/taro-mpharmony/src/api/index.ts
=> fix: 修复开发模式下调用setNavigationStyle报错的问题

packages/taroize/__tests__/template.test.ts, packages/taroize/package.json, packages/taroize/src/template.ts, pnpm-lock.yaml
修复taroize模块的template.test.ts测试用例运行异常问题
=> fix: 修复taroize模块的template.test.ts测试用例运行异常问题

examples/mini-program-example/src/components/callbackContents/index.tsx, examples/mini-program-example/src/pages/api/basics/basics/index.tsx, examples/mini-program-example/src/pages/api/canvas/index.tsx, examples/mini-program-example/src/pages/api/file/index.tsx, examples/mini-program-example/src/pages/api/framework/index.tsx, examples/mini-program-example/src/pages/api/media/audio/index.tsx, examples/mini-program-example/src/pages/api/network/request/index.tsx, examples/mini-program-example/src/util/util.ts
=> feat: 添加function类数据key值挂载，部分添加计时功能

packages/taro-cli-convertor/__tests__/__snapshots__/convertor.test.ts.snap
更新convertor.test.ts快照，修复测试用例运行失败问题
=> fix: 更新convertor.test.ts快照，修复测试用例运行失败问题

packages/taro-cli-convertor/__tests__/__snapshots__/index.test.ts.snap, packages/taro-cli-convertor/__tests__/index.test.ts
固定测试用例中的sourceFilePath，固定根路径为/project，使之能够正确的求取相对路径
=> fix: 修复测试用例中关于求取相对路径的错误，更新对应快照

examples/mini-program-example/src/pages/api/basics/system/index.tsx, packages/taro-mpharmony/src/api/base/system.ts
对getSystemSetting加一个临时缓存，解决频繁调用时此api的耗时问题
=> 对getSystemSetting加一个临时缓存，解决频繁调用时此api的耗时问题

examples/mini-program-example/src/pages/api/media/realtimeAudioAndVideo/index.tsx, packages/taro-components/src/components/live-player/live-player.tsx
修改live-player播放静音无法恢复，补齐测试样例，修复resume多次执行报错
-
）
=> fix: 修改live-player播放静音无法恢复，补齐测试样例，修复resume多次执行报错

packages/taro-mpharmony/src/api/network/download.ts, packages/taro-mpharmony/src/api/network/mdns.ts, packages/taro-mpharmony/src/api/network/request/index.ts, packages/taro-mpharmony/src/api/network/tcp.ts, packages/taro-mpharmony/src/api/network/udp.ts, packages/taro-mpharmony/src/api/network/upload.ts, packages/taro-mpharmony/src/api/network/websocket/index.ts, packages/taro-mpharmony/src/api/network/websocket/socketTask.ts
=> fix: canIUse接口修改及API注释添加

packages/taro-mpharmony/src/api/base/debug/getRealtimeLogManager.ts, packages/taro-mpharmony/src/api/canvas/CanvasContext.ts, packages/taro-mpharmony/src/api/canvas/canvasGetImageData.ts, packages/taro-mpharmony/src/api/canvas/canvasPutImageData.ts, packages/taro-mpharmony/src/api/canvas/canvasToTempFilePath.ts, packages/taro-mpharmony/src/api/media/index.ts, packages/taro-mpharmony/src/api/media/voip.ts, packages/taro-mpharmony/src/api/navigate/index.ts, packages/taro-mpharmony/src/api/network/request/index.ts, packages/taro-mpharmony/src/api/open-api/settings/index.ts, packages/taro-mpharmony/src/api/open-api/user-info/getUserInfo.ts, packages/taro-mpharmony/src/api/ui/interaction/index.ts, packages/taro-platform-mpharmony/build/config/harmony-definition.json, packages/taro-platform-mpharmony/build/definition-json/parseApis.ts
修改API注释问题及补充harmony-definition的API配置
=> fix: 修改API注释问题及补充harmony-definition的API配置

packages/taroize/src/cache.ts, packages/taroize/src/wxml.ts
=> fix: 修复wxml页面混淆问题

packages/taro-cli-convertor/__tests__/__snapshots__/convertor.test.ts.snap, packages/taro-cli-convertor/__tests__/convertor.test.ts, packages/taro-cli-convertor/__tests__/data/fileData.ts
/
补充单文件夹下多wxml页面混淆测试用例，并更正历史用例快照不通过
=> feat: 补充单文件夹下多wxml页面混淆测试用例，并更正历史用例快照不通过

packages/taro-components/src/components/slider/slider.tsx
=> fix: 修复Slider组件无法跨越正负值问题

examples/mini-program-example/src/pages/api/canvas/index.tsx, packages/taro-mpharmony/src/api/canvas/CanvasContext.ts
修改drawImage方法无法使用getImageInfo获取的path作为入参的问题
=> fix: 修改drawImage方法无法使用getImageInfo获取的path作为入参的问题

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/global.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taro-transformer-wx/src/global.ts, packages/taro-transformer-wx/src/index.ts, packages/taro-transformer-wx/src/utils.ts, packages/taro-transformer-wx/src/wxs.ts, packages/taroize/src/global.ts, packages/taroize/src/index.ts, packages/taroize/src/script.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts, packages/taroize/src/vue.ts, packages/taroize/src/wxml.ts
=> fix: 解决转换时日志写入报错，各模块函数新增写入日志

examples/mini-program-example/src/pages/api/basics/miniProgram/applicationLevelEvents/index.tsx
=> fix: 补充on/offAppShow和on/offAppHide测试样例

packages/taro-components/src/components/map/map.tsx
=> fix: 修复自定义图层的非法值透明度问题

examples/mini-program-example/src/pages/api/basics/basics/index.tsx, examples/mini-program-example/src/pages/api/basics/system/index.tsx, examples/mini-program-example/src/pages/api/canvas/index.tsx, examples/mini-program-example/src/pages/api/interface/animation/index.tsx, examples/mini-program-example/src/pages/api/media/map/index.tsx, examples/mini-program-example/src/pages/api/media/realtimeAudioAndVideo/index.tsx, examples/mini-program-example/src/pages/api/network/request/index.tsx, examples/mini-program-example/src/pages/api/openAPIS/subscribeNews/index.tsx, examples/mini-program-example/src/pages/component/map/map.js, examples/mini-program-example/src/pages/component/slider/slider.js, examples/mini-program-example/src/util/util.ts
修复耗时未打印在控制台问题，修复request监听函数undefined问题，format历史代码
=> fix: 修复耗时未打印在控制台问题，修复request监听函数undefined问题，format历史代码

packages/taro-platform-h5/build/utils/ast.ts, packages/taro-platform-mpharmony/build/config/harmony-definition.json
=> fix: 修复H5接口报错问题

packages/taro-cli-convertor/__tests__/__mocks__/fs-extra.js, packages/taro-cli-convertor/__tests__/__snapshots__/script.test.ts.snap, packages/taro-cli-convertor/__tests__/script.test.ts, packages/taro-cli-convertor/src/index.ts
原来convert不支持export from语法，转换会导致文件丢失
新增export from语法支持及测试用例
=> feat: 新增export from语法支持及测试用例

packages/taroize/__tests__/__snapshots__/script.test.ts.snap, packages/taroize/__tests__/script.test.ts
feat: taroize补充plugin路径转换的测试用例，以及对script.test.ts测试的优化
=> feat: taroize补充plugin路径转换的测试用例，以及对script.test.ts测试的优化

packages/taro-components/src/components/map/map.tsx
=> fix: 修复getRotate和getSkew非法值问题

examples/mini-program-example/src/pages/api/device/scan/index.tsx, examples/mini-program-example/src/pages/api/location/index.config.ts, packages/taro-h5/src/api/location/chooseLocation.ts, packages/taro-h5/src/api/location/openLocation.ts, packages/taro-mpharmony/src/api/device/scan.ts, packages/taro-platform-mpharmony/build/config/harmony-definition.json
=> feat: 新增支持一维码二维码扫码能力

packages/taro-components/src/components/map/map.tsx
fix: 修复marker图标高度设置异常、偏移异常、旋转异常
=> fix: 修复marker图标高度设置异常、偏移异常、旋转异常

packages/taro-components/src/components/swiper/readme.md, packages/taro-components/src/components/swiper/swiper.tsx
feat: swiper组件支持currentItemId属性
=> feat: swiper组件支持currentItemId属性

packages/taro-mpharmony/src/api/base/system.ts, packages/taro-mpharmony/src/api/index.ts
=> fix: 修复getSystemInfo返回的系统信息

examples/mini-program-example/src/pages/api/canvas/index.scss, examples/mini-program-example/src/pages/api/canvas/index.tsx, examples/mini-program-example/src/pages/api/framework/index.tsx, examples/mini-program-example/src/pages/api/interface/animation/index.tsx, packages/taro-mpharmony/src/api/ui/navigation-bar/index.ts, packages/taro-router/src/router/page.ts
=> fix: 修改导航栏样式设置方式

examples/mini-program-example/src/pages/api/media/map/index.tsx, examples/mini-program-example/src/pages/component/map/map.js, packages/taro-components/src/components/map/map.tsx
=> fix: 修复中心坐标定位不精确

packages/taro-components/src/components/map/map.tsx
=> fix: 修复图标旋转角度异常

packages/taro-mpharmony/src/api/network/request/index.ts, packages/taro-platform-mpharmony/build/config/harmony-definition.json
=> fix: canIuse中request接口支持情况修改

packages/taro-cli-convertor/__tests__/__snapshots__/convertor.test.ts.snap, packages/taro-cli-convertor/__tests__/convertor.test.ts, packages/taro-cli-convertor/__tests__/data/fileData.ts, packages/taro-cli-convertor/src/index.ts
1.引用小程序插件测试用例，优化测试用例
2.补充测试用例覆盖的代码场景：没有根目录的路径需要拼接处理
- [X ] 错误修复(Bugfix) issue: fix #
- [X ] 微信小程序
=> fix: 补充转换后子组件内部分标签未导入及测试用例

packages/taro-mpharmony/src/api/canvas/canvasGetImageData.ts, packages/taro-mpharmony/src/api/canvas/canvasPutImageData.ts, packages/taro-mpharmony/src/api/media/video/compressVideo.ts, packages/taro-mpharmony/src/api/ui/scroll/index.ts
=> fix: canIUse注释修改

examples/mini-program-example/src/pages/api/openAPIS/login/index.tsx
=> fix: 修复login startTest标记位

packages/taro-components/src/components/map/map.tsx, packages/taro-mpharmony/src/api/media/map/MapContext.ts
修复map组件卡顿和刷新,inlcudePoints超出最小缩放异常
=> fix: 修复map组件卡顿和刷新,inlcudePoints超出最小缩放异常

examples/mini-program-example/src/pages/api/media/realtimeAudioAndVideo/index.tsx, examples/mini-program-example/src/pages/component/live-player/live-player.js, packages/taro-components/__tests__/live-player.spec.tsx, packages/taro-components/src/components/live-player/live-player.tsx, packages/taro-components/src/components/live-player/style/live-player.scss
=> fix: 提供直播流，修改缓冲区测试问题

examples/mini-program-example/src/pages/api/media/map/index.tsx, packages/taro-components/src/components/map/map.tsx
=> fix: 修复callout中的样式异常和movealong功能异常

examples/mini-program-example/src/pages/api/media/image/index.tsx
修改chooseImage的测试样例
fix
鸿蒙（harmony）
=> fix: 修改chooseImage的测试样例

packages/taro-cli-convertor/__tests__/__mocks__/fs-extra.js, packages/taro-cli-convertor/__tests__/__mocks__/path.js, packages/taro-cli-convertor/__tests__/__snapshots__/convertor.test.ts.snap, packages/taro-cli-convertor/__tests__/__snapshots__/index.test.ts.snap, packages/taro-cli-convertor/__tests__/__snapshots__/wxss.test.ts.snap, packages/taro-cli-convertor/__tests__/convertor.test.ts, packages/taro-cli-convertor/__tests__/data/fileData.ts, packages/taro-cli-convertor/__tests__/index.test.ts, packages/taro-cli-convertor/__tests__/wxss.test.ts, packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taroize/package.json
feat: 补充taro-cli-convertor部分测试用例，增量添加mock的fs、path模块
=> feat: 补充taro-cli-convertor部分测试用例，增量添加mock的fs、path模块

examples/mini-program-example/src/pages/api/network/download/index.tsx, packages/taro-mpharmony/src/api/network/download.ts
=> fix: 更改downloadFile接口实现方式

packages/taro-components/src/components/live-player/live-player.tsx, packages/taro-components/src/components/video/video.tsx, packages/taro-mpharmony/src/api/base/system.ts, packages/taro-mpharmony/src/api/index.ts, packages/taro-mpharmony/src/api/media/image/previewImage.ts, packages/taro-mpharmony/src/api/media/image/previewMedia.ts
=> fix: 修复video/live-player进入全屏时导航栏未隐藏的问题

packages/taro-mpharmony/src/api/media/image/previewImage.ts
=> fix: 修复previewImage不显示索引值

packages/taro-cli-convertor/src/index.ts, packages/taro-cli-convertor/src/util/index.ts, packages/taro-transformer-wx/src/index.ts, packages/taro-transformer-wx/src/utils.ts, packages/taro-transformer-wx/src/wxs.ts, packages/taroize/__tests__/__snapshots__/wxml.test.ts.snap, packages/taroize/__tests__/wxml.test.ts, packages/taroize/src/index.ts, packages/taroize/src/script.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts, packages/taroize/src/vue.ts, packages/taroize/src/wxml.ts
fix: 优化日志写入过程、格式、内容、位置等，新增hdc mall问题测试用例
=> fix: 优化日志写入过程、格式、内容、位置等，新增hdc mall问题测试用例

packages/taro-mpharmony/src/api/media/image/chooseImage.ts, packages/taro-mpharmony/src/api/media/video/chooseMedia.ts
=> fix: 修改chooseMedia和chooseImage使用native函数chooseMediaAssets

examples/mini-program-example/src/pages/api/media/map/index.tsx, packages/taro-components/src/components/map/map.tsx, packages/taro-mpharmony/src/api/media/map/MapContext.ts
修复translatemaker移动异常和setboundary限制异常问题
=> fix: 修复translatemaker移动异常和setboundary限制异常问题

packages/taro-components/src/components/live-player/live-player.tsx
=> fix: 修复api退出全屏导航栏不生效问题

examples/mini-program-example/src/util/util.ts
=> fix: 修复回调内容同时含有成功和失败的回调

packages/taro-mpharmony/src/api/media/image/previewImage.ts
=> fix: 修复previewImage中保存图片失败

examples/mini-program-example/src/pages/api/file/index.tsx, packages/taro-mpharmony/src/api/taro.ts
=> feat: window挂载方法base64ToArrayBuffer

packages/taro-mpharmony/src/api/media/video/getVideoInfo.ts
=> fix: 修改视频码率的计算

examples/mini-program-example/src/pages/api/media/video/index.tsx, packages/taro-mpharmony/src/api/media/video/chooseVideo.ts
修改chooseVideo代码和getVedioInfo测试样例传入参数
=> fix: 修改chooseVideo代码和getVedioInfo测试样例传入参数

packages/taro-components/src/components/map/map.tsx, packages/taro-mpharmony/src/api/media/map/MapContext.ts
=> fix: 修复moveAlong和translate错误日志打印

packages/taro-transformer-wx/__tests__/__snapshots__/wxs.test.ts.snap, packages/taro-transformer-wx/__tests__/wxs.test.ts
feat: taro-transformer-wx中wxs.ts文件的测试用例
=> feat: taro-transformer-wx中wxs.ts文件的测试用例

packages/taro-components/src/components/map/map.tsx
修复updateGroundOverlay经纬度坐标与id非法值异常
=> fix: 修复updateGroundOverlay经纬度坐标与id非法值异常

packages/taro-transformer-wx/package.json, packages/taroize/__tests__/__snapshots__/index.test.ts.snap, packages/taroize/__tests__/__snapshots__/script.test.ts.snap, packages/taroize/__tests__/__snapshots__/wxml.test.ts.snap, packages/taroize/__tests__/event.test.ts, packages/taroize/__tests__/index.test.ts, packages/taroize/__tests__/script.test.ts, packages/taroize/__tests__/template.test.ts, packages/taroize/__tests__/utils.test.ts, packages/taroize/__tests__/wxml.test.ts, packages/taroize/src/global.ts, packages/taroize/src/index.ts, packages/taroize/src/template.ts, packages/taroize/src/utils.ts, packages/taroize/src/wxml.ts
将taroize文档jest测试用例提升90%
补充了部分日志测试用例，删除了isAliasThis 函数（未被调用）
- [X ] 错误修复(Bugfix) issue: fix #
- [ X] 微信小程序
=> feat: taroize的部分日志测试用例补充

packages/taro-mpharmony/src/api/interface/NativeFileSystemManager.ts
=> fix: 新通道增加readFile(Sync)实现

examples/mini-program-example/src/pages/api/media/map/index.tsx, examples/mini-program-example/src/pages/component/map/map.js, packages/taro-components/__tests__/map.spec.tsx, packages/taro-components/src/components/map/map.tsx
=> fix: 修复地图全屏样式限制

packages/taro-mpharmony/src/api/NativeApi.ts, packages/taro-mpharmony/src/api/index.ts
=> feat: 桥接setNavigationStyle接口

packages/taro-mpharmony/src/api/NativeApi.ts, packages/taro-mpharmony/src/api/open-api/subscribe-message.ts
=> feat: 桥接requestSubscribeMessage接口

packages/taro-mpharmony/src/api/NativeApi.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/closeBLEConnection.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/createBLEConnection.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/getBLEDeviceCharacteristics.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/getBLEDeviceRSSI.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/getBLEDeviceServices.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/notifyBLECharacteristicValueChange.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/onBLECharacteristicValueChange.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/onBLEConnectionStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/readBLECharacteristicValue.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/setBLEMTU.ts, packages/taro-mpharmony/src/api/device/bluetooth-ble/writeBLECharacteristicValue.ts, packages/taro-mpharmony/src/api/device/bluetooth/closeBluetoothAdapter.ts, packages/taro-mpharmony/src/api/device/bluetooth/getBluetoothAdapterState.ts, packages/taro-mpharmony/src/api/device/bluetooth/getBluetoothDevices.ts, packages/taro-mpharmony/src/api/device/bluetooth/getConnectedBluetoothDevices.ts, packages/taro-mpharmony/src/api/device/bluetooth/offBluetoothAdapterStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth/offBluetoothDeviceFound.ts, packages/taro-mpharmony/src/api/device/bluetooth/onBluetoothAdapterStateChange.ts, packages/taro-mpharmony/src/api/device/bluetooth/onBluetoothDeviceFound.ts, packages/taro-mpharmony/src/api/device/bluetooth/openBluetoothAdapter.ts, packages/taro-mpharmony/src/api/device/bluetooth/startBluetoothDevicesDiscovery.ts, packages/taro-mpharmony/src/api/device/bluetooth/stopBluetoothDevicesDiscovery.ts
=> feat: 桥接部分蓝牙模块功能

packages/taro-mpharmony/src/api/NativeApi.ts, packages/taro-mpharmony/src/api/open-api/settings/getSetting.ts, packages/taro-mpharmony/src/api/open-api/settings/openSetting.ts
修复getSetting和openSetting桥接错误问题以及修复nativeApi中桥接字段isAsync错误问题
=> fix: 修复getSetting和openSetting桥接错误问题以及修复nativeApi中桥接字段isAsync错误问题

examples/mini-program-example/src/pages/index/index.tsx, examples/mini-program-example/src/util/nativeApi.ts, packages/taro-mpharmony/src/api/NativeApi.ts
=> fix: 修复mini-program-example下运行run dev:mpharmony时的jsBridgeMode报错问题

packages/taro-mpharmony/src/api/NativeApi.ts, packages/taro-mpharmony/src/api/network/request/index.ts
=> 部分api支持osChannel

packages/taro-mpharmony/src/api/storage/index.ts
=> fix: 修复数据共享数据取出是对象的问题

packages/taro-mpharmony/src/api/network/request/index.ts, packages/taro-mpharmony/src/index.ts
=> fix: taro js侧日志打印改造

packages/taro-mpharmony/src/api/NativeApi.ts, packages/taro-mpharmony/src/api/network/request/index.ts, packages/taro-mpharmony/src/api/request.ts
=> fix: request接口jsb和纯js实现转换

packages/taro-router/src/style.ts
=> fix: 解决打开第1个页面时在鸿蒙平台动画不能真正的停止的问题

packages/taro-router/src/router/page.ts, packages/taro-router/src/router/spa.ts
=> fix: 解决返回时上一个页面瞬间白屏的问题

packages/taro-platform-harmony-hybrid/src/api/apis/NativeApi.ts, packages/taro-platform-harmony-hybrid/src/api/apis/NativeApiSyncCacheProxy.ts
=> feat: taro同步方法支持缓存
